### ISSUE TITLE
Unit Test-one idea about TeXmacs

### ISSUE THREAD

**Issue by HYWZ36** [texmacs/gsoc#1]
**Unit testing**, also known as module testing, is a test for correctness testing of program modules. It can effectively help developers reduce bugs, improve development efficiency, ensure code compatibility, improve code quality, and better maintain code.
The program is initially intended to introduce Google's open source C++ unit testing framework-**Google Test**. Google Test's testing technology is very mature, and the feedback results are also user-friendly, so it is convenient for people to get started faster, and also for developers to analyze and solve code problems.
Based on this, I built a subproject-**collection**, initially integrated the unit test framework Google Test. After a simple test, the results are correct. Some students have been interested in this subproject and submitted a pull request and several issues after analysis. So I think this idea can be implemented very well.
Also, a few months ago, I saw a TeXmacs **memory technology** (https://www.douban.com/doubanapp/dispatch?uri=/group/topic/105715564&dt_dapp=1&dt_platform=com.douban.activity.Qq_session). Perhaps through unit testing analysis, TeXmacs can be further optimized, such as the memory allocation technology of the open source project jemalloc.

**Comment by da-liii** [comment]
Well, decoupling is the first step to explore a big project.
