### ISSUE TITLE
Are the conversion options between programming languages and TeXmacs unwanted?

### ISSUE THREAD

**Issue by Blickwinkel1107** [texmacs/gsoc#3]
Hi. I'm an applicant of GSoC 2020 and I was trying some import/export options. (just some ready-ups for improvement). The options read that I can convert my TeXmacs doc to programming language source code, like C++, Scala or something. But I don't know what the differences between these. 
However I tried to export .cpp, .py and .java file. The only difference that I found is about their file suffixes, and everything in export content is the same.
Actually I don't know what's the relationship between TeXmacs and programming languages. I think the truth is that TeXmacs regards the conversion as "convert to plain text".
In my point of view, these conversion options to different languages can be removed, or, as an alternative, can be summarized as "export to code file".

**Comment by da-liii** [comment]
We only talk about anything about gsoc here. For general TeXmacs topics, please use the Developers' mail list.
